version: '3'
services: 
  bangunsite: 
    image: bangunsite:1.0
    container_name: bangunsite
    privileged: true
    cpus: 0.5
    mem_limit: 256m
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "127.0.0.1:7080:80"
      - "127.0.0.1:7443:443"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:13999:13999"
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    volumes:
      - /etc/hosts:/etc/hosts
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/storage:rw
      # development
      - ./web/app:/app/app
      - ./web/database:/app/database
      - ./web/public:/app/public
      - ./web/resources:/app/resources
      - ./web/routes:/app/routes
    networks:
      - bangunsite

  mail-server:
    image: dockage/mailcatcher:0.9.0
    container_name: mail-server
    ports:
      - "127.0.0.1:8081:1080"
    networks:
      - bangunsite

networks:
  bangunsite:
    external: true
    name: cloudflared_bangunsoft
