global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'VM-stats'
rule_files:
  # - "alert.rules"
  # - "first.rules"
  # - "second.rules"
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090', 'bangunsite-node-exporter:9100']