name: BangunSite Build Action

env:
  IMAGE_NAME: bangunsite:latest

on: push

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: docker build -f Dockerfile-prod --tag ${{ env.IMAGE_NAME }} .
    - name: Test run
      run: docker run -d --name bangunsite ${{ env.IMAGE_NAME }}
    - name: Wait for docker to finish building
      run: sleep 5
    - name: Check healty
      run: |
        docker exec -i bangunsite curl http://localhost/healty.php -s --connect-timeout 10
        docker exec -i bangunsite artisan key:generate
        docker exec -i bangunsite curl http://localhost:8000 -Isf --connect-timeout 10
