name: BangunSite Build Action

env:
  IMAGE_NAME: bangunsite:latest

on: push

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        docker build -f Dockerfile-prod --tag ${{ env.IMAGE_NAME }} .
