name: BangunSite Build Action

env:
  IMAGE_NAME: bangunsite:latest

on: push

jobs:
  hadolin:
    name: hadolint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile-prod

  healty:
    needs: hadolin
    name: Healty check
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && success()

    steps:
    - uses: actions/checkout@main
    - name: Build
      run: docker build -f Dockerfile-prod --tag ${{ env.IMAGE_NAME }} .
    - name: Test run
      run: docker run -d --name bangunsite ${{ env.IMAGE_NAME }}
    - name: Wait for docker to finish building
      run: sleep 5
    - name: Check healty
      run: |
        docker exec -i bangunsite curl localhost/healty.php -s --connect-timeout 10
        docker exec -i bangunsite artisan key:generate > /dev/null && sleep 5
        docker exec -i bangunsite curl localhost:8000/healty -sf --connect-timeout 10
        docker stop bangunsite > /dev/null
        docker rm bangunsite > /dev/null
        docker rmi ${{ env.IMAGE_NAME }} > /dev/null